# Generated by Django 3.2 on 2021-05-07 10:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Druh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaceni_druhu', models.CharField(help_text='Zadejte text o maximální délce 50 znaků; text musí být jedinečný', max_length=50, unique=True, verbose_name='Označení druhu nábytku')),
                ('oblast', models.CharField(blank=True, choices=[('postele', 'Postele'), ('pohovky', 'Pohovky'), ('knihovny a policové díly', 'Knihovny a policové díly'), ('stoly', 'Stoly'), ('skříňky a příborníky', 'Skříňky a příborníky')], default='postele', help_text='Vyberte označení oblasti', max_length=50, verbose_name='Oblast')),
            ],
            options={
                'verbose_name': 'Druh nábytku',
                'verbose_name_plural': 'Druh nábytku',
                'ordering': ['oznaceni_druhu'],
            },
        ),
        migrations.CreateModel(
            name='Nabytek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, verbose_name='Název nábytku')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis nábytku')),
                ('cena', models.FloatField(help_text='Zadejte nezáporné desetinné číslo', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cena')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='zbozi/%Y/%m/%d/', verbose_name='Fotka nábytku')),
                ('druh', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ikea.druh')),
            ],
            options={
                'verbose_name': 'Nábytek',
                'verbose_name_plural': 'Nábytek',
                'ordering': ['-cena', 'nazev'],
            },
        ),
    ]
